### ISSUE TITLE
BpmAnalyser not outputting BPM Values

### ISSUE THREAD

**Issue by OannesGPT** [adamjakab/BeetsPluginBpmAnalyser#18]
### Problem

Running your command in verbose (`-vv`) mode:

```sh
beet bpmanalyser --dry-run title:Tripura - Wizard Project

```

Led to this problem:

```
bpmanalyser: BpmAnalyser exec threads: 6
bpmanalyser: Done.

```

### Setup

* OS:  W10
* Python version: 3.13
* Beets version: Latest
* Turning off other plugins made problem go away (yes/no):  no

My configuration (output of `beet config`) is:

```yaml
directory: C:/Users/Hannes/Desktop/Test
library: C:/Users/Hannes/AppData/Roaming/beets/library.db
import:
  copy: yes
  write: yes
  move: no

plugins:
  - bpmanalyser

bpmanalyser:
  auto: no
  dry-run: no
  write: yes
  threads: "AUTO"
  force: no
  quiet: no

logging:
  level: DEBUG

```

My plugin version (output of `beet bpmanalyser -v`) is:

```text
bpmanalyser: Bpm Analyser(beets-bpmanalyser) plugin for Beets: v1.5.9
```
