### ISSUE TITLE
Not working on import

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [adamjakab/BeetsPluginBpmAnalyser#9]
### Problem

First of all awesome job with the script. It works with `beet -vv bpmanalyser whatever` and 

```
plugins: fetchart embedart lyrics discogs spotify convert bpmanalyser replaygain
autotag: yes
ignore_hidden: yes
original_date: yes
languages: en
va_name: Compilation
directory: /redacted/
import:
    copy: yes
    write: yes
    move: no
convert:
    auto: yes
    quiet: yes
    delete_originals: no
    format: mp3
    mp3:
      command: ffmpeg -i $source -q:a 0 -map_metadata 0 $dest
      extension: mp3
discogs:
    user_token: redacted
fetchart:
    auto: yes
    sources: fanarttv itunes amazon coverart albumart
    fanarttv_key: redacted
embedart: 
    auto: yes
    maxwidth: 1000
    remove_art_file: yes
lyrics:
    auto: yes
    force: yes
    import.write: yes
    sources: genius
    google_API_key: redacted
replaygain:
  auto: yes
  overwrite: yes
bpmanalyser:
  auto: yes
  dry-run: no
  write: yes
  threads: 2
  force: yes
  quiet: yes
replace:
    'featuring': 'feat\.'
    '’': "'"
    '[“”]': '"'
    '[…]': '...'
    '[-]': '-'
    '[−]': '-'
    '[—]': '-'
    '[Ⅰ]': I
    '[Ⅱ]': II
```

However, on import, no tag is written to the files automatically.

### Setup

* OS: macOS
* Python version: 3.9.5
* Beets version: 1.6.1
